window.esdocSearchIndex = [
  [
    "detherjs/src/constants/appconstants.js~coord_precision",
    "variable/index.html#static-variable-COORD_PRECISION",
    "<span>COORD_PRECISION</span> <span class=\"search-result-import-path\">detherjs/src/constants/appConstants.js</span>",
    "variable"
  ],
  [
    "detherjs/src/utils/contracts.js~contracts",
    "variable/index.html#static-variable-Contracts",
    "<span>Contracts</span> <span class=\"search-result-import-path\">detherjs/src/utils/contracts.js</span>",
    "variable"
  ],
  [
    "detherjs/src/detherjs.js~detherjs",
    "class/src/detherJs.js~DetherJS.html",
    "<span>DetherJS</span> <span class=\"search-result-import-path\">detherjs/src/detherJs.js</span>",
    "class"
  ],
  [
    "detherjs/src/detheruser.js~detheruser",
    "class/src/detherUser.js~DetherUser.html",
    "<span>DetherUser</span> <span class=\"search-result-import-path\">detherjs/src/detherUser.js</span>",
    "class"
  ],
  [
    "detherjs/src/constants/appconstants.js~gas_price",
    "variable/index.html#static-variable-GAS_PRICE",
    "<span>GAS_PRICE</span> <span class=\"search-result-import-path\">detherjs/src/constants/appConstants.js</span>",
    "variable"
  ],
  [
    "detherjs/src/utils/eth.js~add0x",
    "function/index.html#static-function-add0x",
    "<span>add0x</span> <span class=\"search-result-import-path\">detherjs/src/utils/eth.js</span>",
    "function"
  ],
  [
    "detherjs/src/utils/eth.js~isaddr",
    "function/index.html#static-function-isAddr",
    "<span>isAddr</span> <span class=\"search-result-import-path\">detherjs/src/utils/eth.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/constants/appconstants.js",
    "file/src/constants/appConstants.js.html",
    "src/constants/appConstants.js",
    "file"
  ],
  [
    "src/detherjs.js",
    "file/src/detherJs.js.html",
    "src/detherJs.js",
    "file"
  ],
  [
    "src/detherjs.js~detherjs#constructor",
    "class/src/detherJs.js~DetherJS.html#instance-constructor-constructor",
    "src/detherJs.js~DetherJS#constructor",
    "method"
  ],
  [
    "src/detherjs.js~detherjs#getalltellers",
    "class/src/detherJs.js~DetherJS.html#instance-method-getAllTellers",
    "src/detherJs.js~DetherJS#getAllTellers",
    "method"
  ],
  [
    "src/detherjs.js~detherjs#getteller",
    "class/src/detherJs.js~DetherJS.html#instance-method-getTeller",
    "src/detherJs.js~DetherJS#getTeller",
    "method"
  ],
  [
    "src/detherjs.js~detherjs#gettellerbalance",
    "class/src/detherJs.js~DetherJS.html#instance-method-getTellerBalance",
    "src/detherJs.js~DetherJS#getTellerBalance",
    "method"
  ],
  [
    "src/detherjs.js~detherjs#gettellersinzone",
    "class/src/detherJs.js~DetherJS.html#instance-method-getTellersInZone",
    "src/detherJs.js~DetherJS#getTellersInZone",
    "method"
  ],
  [
    "src/detherjs.js~detherjs#getuser",
    "class/src/detherJs.js~DetherJS.html#instance-method-getUser",
    "src/detherJs.js~DetherJS#getUser",
    "method"
  ],
  [
    "src/detheruser.js",
    "file/src/detherUser.js.html",
    "src/detherUser.js",
    "file"
  ],
  [
    "src/detheruser.js~detheruser#addsellpoint",
    "class/src/detherUser.js~DetherUser.html#instance-method-addSellPoint",
    "src/detherUser.js~DetherUser#addSellPoint",
    "method"
  ],
  [
    "src/detheruser.js~detheruser#address",
    "class/src/detherUser.js~DetherUser.html#instance-member-address",
    "src/detherUser.js~DetherUser#address",
    "member"
  ],
  [
    "src/detheruser.js~detheruser#constructor",
    "class/src/detherUser.js~DetherUser.html#instance-constructor-constructor",
    "src/detherUser.js~DetherUser#constructor",
    "method"
  ],
  [
    "src/detheruser.js~detheruser#deletesellpoint",
    "class/src/detherUser.js~DetherUser.html#instance-method-deleteSellPoint",
    "src/detherUser.js~DetherUser#deleteSellPoint",
    "method"
  ],
  [
    "src/detheruser.js~detheruser#getaddress",
    "class/src/detherUser.js~DetherUser.html#instance-method-getAddress",
    "src/detherUser.js~DetherUser#getAddress",
    "method"
  ],
  [
    "src/detheruser.js~detheruser#getbalance",
    "class/src/detherUser.js~DetherUser.html#instance-method-getBalance",
    "src/detherUser.js~DetherUser#getBalance",
    "method"
  ],
  [
    "src/detheruser.js~detheruser#getinfo",
    "class/src/detherUser.js~DetherUser.html#instance-method-getInfo",
    "src/detherUser.js~DetherUser#getInfo",
    "method"
  ],
  [
    "src/detheruser.js~detheruser#sendtobuyer",
    "class/src/detherUser.js~DetherUser.html#instance-method-sendToBuyer",
    "src/detherUser.js~DetherUser#sendToBuyer",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/utils/contracts.js",
    "file/src/utils/contracts.js.html",
    "src/utils/contracts.js",
    "file"
  ],
  [
    "src/utils/eth.js",
    "file/src/utils/eth.js.html",
    "src/utils/eth.js",
    "file"
  ],
  [
    "src/utils/formatters.js",
    "file/src/utils/formatters.js.html",
    "src/utils/formatters.js",
    "file"
  ],
  [
    "src/utils/providers.js",
    "file/src/utils/providers.js.html",
    "src/utils/providers.js",
    "file"
  ],
  [
    "src/utils/validation.js",
    "file/src/utils/validation.js.html",
    "src/utils/validation.js",
    "file"
  ]
]